### PR TITLE
Use File Object instead filename

### PR DESCRIPTION
**Pull request by velios**
First of all, thank you for your work.

This is draft PR. I will prepare it for uploading to the main if you confirm that you are not conceptually against the proposed changes.
Changes will help to use library in http services, which take data from resources. And maybe in other cases. For example, I came across the fact that I can read a file from resources in the following way in my project.
```clojure
(require '[clojure.java.io :as io])
(def file (io/file (io/resource file-name)))
```
But I can't directly pass the filename. Therefore, I propose to support file object transfer with minimal changes.

### CODE REVIEW

**Review by kbosompem — APPROVED** [review]
Thanks!

**Comment by velios** [comment]
> Thanks!

Do you want me to complete the implementation of this task or do you like the idea and will implement it yourself? What should I do? PR cannot be used without modifications, it's only concept, not yet realization.

**Comment by kbosompem** [comment]
> > Thanks!
> 
> Do you want me to complete the implementation of this task or do you like the idea and will implement it yourself? What should I do? PR cannot be used without modifications, it's only concept, not yet realization.

I'd love to do it but won't be able to get to it for a couple of weeks. Do you have the bandwidth to handle it before then?

**Comment by velios** [comment]
> I'd love to do it but won't be able to get to it for a couple of weeks. Do you have the bandwidth to handle it before then?

Yes, I will try. The task doesn't look difficult. Only in the part where I need to maintain backward compatibility for all functions. I hope you will be in touch to discuss if there are any controversial issues in my proposals.

**Comment by kbosompem** [comment]
> > I'd love to do it but won't be able to get to it for a couple of weeks. Do you have the bandwidth to handle it before then?
> 
> Yes, I will try. The task doesn't look difficult. Only in the part where I need to maintain backward compatibility for all functions. I hope you will be in touch to discuss if there are any controversial issues in my proposals.

Absolutely!

**Comment by velios** [comment]
Move discussion to [PR-4](https://github.com/kbosompem/bb-excel/pull/5)

**Pull request closed without merging**
